import json
import sys

import click

from agentcad.runners import dispatch


# Runtime-agnostic sections — same content regardless of which engine is in
# play. (commands, render, schema, export, validation, metrics, inspect,
# daemon, parts, mcp, install, workflow.)
#
# Runtime-specific sections live in CADQUERY_OVERLAY and BUILD123D_OVERLAY
# below. ``get_sections(runtime)`` merges the relevant overlay onto SECTIONS.
SECTIONS = {
    "install": (
        "Installation:\n"
        "  Requires Python 3.10-3.12 (OpenCascade bindings do not support 3.13+).\n"
        "\n"
        "  pip install agentcad\n"
        "\n"
        "  This installs agentcad and all dependencies (CadQuery, OpenCascade, Click)\n"
        "  automatically. No separate package installation is needed.\n"
        "\n"
        "  After installing, the 'agentcad' command is available in your shell.\n"
        "  Run 'agentcad docs' to see full documentation.\n"
    ),
    "quickstart": (
        "Quickstart:\n"
        "  1. Initialize a project:\n"
        "     agentcad init --name myproject\n"
        "\n"
        "  2. Write a script (no imports needed — cq is pre-injected):\n"
        "     box = cq.Workplane('XY').box(10, 20, 5)\n"
        "     show_object(box)\n"
        "\n"
        "  3. Run it:\n"
        "     agentcad run script.py --output first_box\n"
        "     The default --preview produces a 4-view composite PNG (preview.png)\n"
        "     and viewer.html; --render is only needed for extra camera angles.\n"
        "\n"
        "  Multi-part example (multiple show_object() calls):\n"
        "     base = cq.Workplane('XY').box(50, 50, 5)\n"
        "     show_object(base)\n"
        "     pin = cq.Workplane('XY').workplane(offset=5).circle(3).extrude(10)\n"
        "     show_object(pin)\n"
        "\n"
        "  Named parts — give each part an identity and color:\n"
        "     show_object(base, name=\"base\", options={\"color\": \"gray\"})\n"
        "     show_object(pin, name=\"pin\", options={\"color\": \"blue\"})\n"
        "     See 'agentcad docs parts' for details.\n"
        "\n"
        "  Multiple show_object() calls become a `parts` array in the run output\n"
        "  (with per-part metrics and previews) plus a single compound STEP file.\n"
        "  Name parts with `name=...` to key them meaningfully; see docs parts.\n"
    ),
    "commands": (
        "agentcad commands:\n"
        "  init    — Initialize a new agentcad project (creates agentcad.json).\n"
        "  run     — Execute a build123d or CadQuery script, produce versioned STEP output.\n"
        "            Always produces: STEP, GLB, viewer.html, and (from v2) diff PNGs.\n"
        "            Options: --render, --export, --no-preview (skips only the 4-view composite)\n"
        "  render  — Render PNG views of an existing STEP file.\n"
        "  export  — Export an existing STEP file to mesh formats (STL, GLB).\n"
        "  measure — Measure overall dimensions and feature sizes in STEP/BREP files.\n"
        "            Full feature output is capped by default; use --no-limit explicitly.\n"
        "  check-spec\n"
        "          — Compare measured cylindrical features against an explicit JSON spec.\n"
        "  parts   — List/show parts captured for a version snapshot, or generate\n"
        "            part review viewers with hide/isolate/ghost/focus state.\n"
        "  view    — Open a GLB or STEP file in the browser (three.js viewer).\n"
        "            Use --measure or --spec spec.json for read-only measurement review.\n"
        "  context — Show the current project state (versions, current label).\n"
        "  docs    — Show this documentation.\n"
        "  diff    — Compare two versions of a model.\n"
        "  inspect — Inspect STEP file topology (shells, faces, edges).\n"
        "            --ids output is capped by default; use --no-limit explicitly.\n"
        "  feedback\n"
        "          — Send an observation to the agentcad team (any friction,\n"
        "            any time — bundles your session log automatically).\n"
    ),
    "render": (
        "Rendering:\n"
        "  agentcad render <step_file> --view <spec> [--zoom N] [--size WxH] "
        "[--msaa N] [--name label] [--focus x,y,z] [--no-fit]\n"
        "\n"
        "  --view   Named views (front, back, left, right, top, bottom, iso),\n"
        "           comma-separated, 'all', or custom 'azimuth,elevation'.\n"
        "  --zoom   Zoom factor applied after FitAll (default 1.0).\n"
        "  --size   Output resolution as WIDTHxHEIGHT (default 800x600).\n"
        "  --msaa   Antialiasing samples, 0-16 (default 0). Nonzero values also\n"
        "           use 2x supersampling to ensure offscreen antialiasing.\n"
        "  --focus  Camera target point as 'x,y,z'.\n"
        "  --no-fit Skip FitAll (requires --focus).\n"
        "  --name   Custom filename for single-view renders.\n"
    ),
    "schema": (
        "Response schema:\n"
        "  All commands return JSON with 'command' and 'status' fields.\n"
        "\n"
        "  Status values:\n"
        "    success — The command completed normally. Per-command fields below.\n"
        "    failed  — A script execution failed (e.g. CadQuery error, no show_object).\n"
        "              Includes 'error' field with details. A version directory is created.\n"
        "    error   — A CLI-level error (missing file, bad arguments, no manifest).\n"
        "              Includes 'message' field. No disk artifacts are created.\n"
        "    CAD file readers may also return non-success diagnostic statuses:\n"
        "              empty, malformed, unknown_format, display_format,\n"
        "              recognized_deferred, or limited. These include message and/or\n"
        "              suggestion fields plus detected file metadata when available.\n"
        "\n"
        "  Artifact key convention (used everywhere — command output, meta.json, diff):\n"
        "    outputs — dict of explicit 3D model artifacts. Keys: step, script,\n"
        "              stl, glb, obj. outputs.glb appears only when --export glb\n"
        "              was requested; viewer_glb is the always-written GLB backing\n"
        "              viewer.html.\n"
        "    renders — dict of 2D PNG renders. Keys: view name (iso, front, top, ...) or\n"
        "              custom angle key ('45_30') or --name override.\n"
        "    Both are present when populated; commands that only produce one kind only\n"
        "    return that key. Do NOT look for 'renders' inside 'outputs' or vice versa.\n"
        "\n"
        "  Per-command response fields (on status='success'):\n"
        "    init     project, runtime?\n"
        "    run      runtime, output_type, version, label, outputs, metrics, params?, warnings?,\n"
        "             preview?, diff?, viewer?, viewer_glb?, renders?, timings\n"
        "    export   outputs                          (3D mesh formats only)\n"
        "    render   renders                          (PNG views only)\n"
        "    inspect  file, format_detected, extension, size_bytes,\n"
        "             solid_count, shell_count, shells, face_count,\n"
        "             face_orientations, edge_count, free_edge_count, is_valid,\n"
        "             next_actions, more_at, notes?, validity_errors?,\n"
        "             solids?/faces?/edges? (--ids), summary? (--summary),\n"
        "             truncation?, edit_risk?/risk_reasons?/recommended_workflow?\n"
        "    measure  file, format_detected, extension, size_bytes, metrics,\n"
        "             cylindrical_features, feature_summary?,\n"
        "             features? (--features only), query?, truncation?,\n"
        "             next_actions, more_at, notes?,\n"
        "             edit_risk?/risk_reasons?/recommended_workflow?\n"
        "    check-spec\n"
        "             file, spec_file, passed, matched_features, missing_features,\n"
        "             total_abs_count_error, validity, metrics\n"
        "    view     url, model | mode, url, model_a, model_b, png?\n"
        "    parts   version, label, viewer?, viewer_glb?, parts[] / part\n"
        "    diff     v1, v2, changes (with 'outputs', 'renders', 'metrics', 'parts'?\n"
        "             subkeys), visual?\n"
    ),
    "export": (
        "Exporting mesh formats:\n"
        "  agentcad export <step_file> --format stl,glb,obj\n"
        "  agentcad run script.py --output label --export stl,glb,obj\n"
        "\n"
        "  Supported formats: stl, glb, obj\n"
        "  Files are written alongside the STEP file.\n"
        "  In a version directory, meta.json outputs are updated.\n"
        "\n"
        "  In scripts, you can also import directly:\n"
        "    from agentcad.export import export_glb\n"
        "    export_glb(shape, 'output.glb')  # shape must be a TopoDS_Shape\n"
        "\n"
        "  STL export uses CadQuery's built-in exporter.\n"
        "  GLB export auto-colors individual solids — each part gets a distinct\n"
        "  color from a built-in palette for easy identification in 3D viewers.\n"
        "  GLB export handles tessellation automatically — do not use\n"
        "  cadquery.exporters.export() for GLTF/GLB (it is not supported).\n"
    ),
    "validation": (
        "Pre-execution validation:\n"
        "  Before building geometry, 'agentcad run' performs fast static checks.\n"
        "  Failures return immediately (<100ms) with status 'validation_error',\n"
        "  without consuming a version number or creating disk artifacts.\n"
        "\n"
        "  Checks:\n"
        "    syntax_error        Python syntax validation (ast.parse)\n"
        "    show_object_missing Script must call show_object() to surface geometry\n"
        "    import_error        All imported modules must be resolvable\n"
        "\n"
        "  Output format:\n"
        "    {\"command\": \"run\", \"status\": \"validation_error\",\n"
        "     \"checks\": [{\"check\": \"...\", \"severity\": \"error\", \"message\": \"...\"}]}\n"
    ),
    "preamble": (
        "Script preamble (pre-injected names):\n"
        "  Every script executed by 'agentcad run' has the following names\n"
        "  available without any import statements:\n"
        "\n"
        "  cq             cadquery module (import cadquery as cq)\n"
        "  show_object    CQGI's show_object function\n"
        "  loft_sections  agentcad.helpers.loft_sections\n"
        "  tapered_sweep  agentcad.helpers.tapered_sweep\n"
        "  naca_wire      agentcad.helpers.naca_wire\n"
        "  mirror_fuse    agentcad.helpers.mirror_fuse\n"
        "  translate      agentcad.helpers.translate\n"
        "  rotate         agentcad.helpers.rotate\n"
        "  bbox_point          agentcad.helpers.bbox_point\n"
        "  place_at            agentcad.helpers.place_at\n"
        "  assemble            agentcad.helpers.assemble\n"
        "  ellipse_wire        agentcad.helpers.ellipse_wire\n"
        "  spline_wire         agentcad.helpers.spline_wire\n"
        "  polygon_wire        agentcad.helpers.polygon_wire\n"
        "  rounded_rect_wire   agentcad.helpers.rounded_rect_wire\n"
        "  elliptical_sweep    agentcad.helpers.elliptical_sweep\n"
        "  annular_boss        agentcad.helpers.annular_boss\n"
        "  raise_annulus       agentcad.helpers.raise_annulus\n"
        "  involute_gear_profile agentcad.helpers.involute_gear_profile\n"
        "\n"
        "  Explicit imports still work — adding 'import cadquery as cq' is harmless.\n"
        "  For non-standard modules (e.g. OCP.gp), you still need explicit imports.\n"
    ),
    "metrics": (
        "Geometric metrics:\n"
        "  Every successful 'agentcad run' returns a 'metrics' key with:\n"
        "\n"
        "  bounding_box   {x: [min,max], y: [min,max], z: [min,max]}\n"
        "  dimensions     {x: float, y: float, z: float}  (bbox extents)\n"
        "  volume         float (mm^3)\n"
        "  surface_area   float (mm^2)\n"
        "  center_of_mass {x, y, z}\n"
        "  face_count     int\n"
        "  edge_count     int\n"
        "  is_valid       bool (OCP shape validity)\n"
        "\n"
        "  Metrics are also saved in meta.json and compared by 'agentcad diff'.\n"
        "  Use metrics to verify shape correctness without rendering.\n"
        "\n"
        "  Units: agentcad is unit-agnostic. All dimensions, volume, and area\n"
        "  are reported in whatever units your script uses. CadQuery defaults\n"
        "  to millimeters, so volume is mm^3 and area is mm^2 unless you\n"
        "  chose a different convention in your script.\n"
    ),
    "measure": (
        "Measurement workflow:\n"
        "  Use measure when the question is dimensional: overall size, edge\n"
        "  lengths, face areas, hole diameters, cylindrical boss diameters, or\n"
        "  feature counts by type.\n"
        "\n"
        "  Basic dimensional report:\n"
        "    agentcad measure v1_label/output.step\n"
        "    If you just ran the model, run.metrics.dimensions is enough for\n"
        "    overall size; use measure for existing STEP files or feature-level\n"
        "    dimensions.\n"
        "\n"
        "  Response fields:\n"
        "    file / format_detected / extension / size_bytes\n"
        "                     Source file metadata.\n"
        "    metrics          Same aggregate metrics as run: bounding_box,\n"
        "                     dimensions, volume, surface_area, center_of_mass,\n"
        "                     face_count, edge_count, is_valid.\n"
        "                     metrics.is_valid is the authoritative shape\n"
        "                     validity bit; validity_errors and warnings also\n"
        "                     live under metrics when present.\n"
        "    cylindrical_features\n"
        "                     Neutral cylinder inventory grouped by diameter and\n"
        "                     axis: diameter_mm, count, axis (+x/+y/+z/other),\n"
        "                     representative_centers, direction? (only for other).\n"
        "    feature_summary  Compact clusters of faces/edges. Cylindrical faces\n"
        "                     and circular edges include radius and diameter.\n"
        "                     Omitted by --cylinders-only.\n"
        "                     Shape: face_count, edge_count, face_clusters,\n"
        "                     edge_clusters, id_truncation?.\n"
        "                     Cluster fields include ids, count, axis?, radius?,\n"
        "                     diameter?, area_mean/min/max?, length_mean?,\n"
        "                     surface_type?, curve_type?, ids_total?,\n"
        "                     ids_omitted?, ids_truncated?.\n"
        "    query            Echoes --cylinders-only, --axis, and --diameter\n"
        "                     with diameter_tolerance_mm when present.\n"
        "    features         Full per-solid, per-face, and per-edge lists;\n"
        "                     emitted only with --features and omitted by\n"
        "                     --cylinders-only.\n"
        "    truncation       Present when feature_summary or features lists are\n"
        "                     capped by --limit/default limits.\n"
        "    next_actions / more_at\n"
        "                     Agent-facing follow-up commands and docs pointer.\n"
        "    notes            Contextual clarifications when measurements need\n"
        "                     domain context, such as a zero-solid surface input.\n"
        "    edit_risk / risk_reasons / recommended_workflow\n"
        "                     Emitted only for risky imports (invalid and/or\n"
        "                     large topology). 'high' means do NOT start with\n"
        "                     load_step() + boolean/fillet edits; see\n"
        "                     `agentcad docs inspect` for the full rubric.\n"
        "\n"
        "  This is a measured feature inventory, not a manufacturing tolerance\n"
        "  checker and not a full CAD feature tree. It reports neutral cylinders;\n"
        "  it does not claim hole vs boss in Slice 1.\n"
        "  To compare those measurements against intended requirements, write a\n"
        "  JSON feature spec and run `agentcad check-spec`.\n"
        "\n"
        "  Full per-feature measurements:\n"
        "    agentcad measure v1_label/output.step --features\n"
        "    Adds features.solids[], features.faces[], features.edges[]. Use this\n"
        "    when you need exact face areas, face centroids/normals/bboxes, or\n"
        "    individual edge lengths/endpoints. Lists are capped at 100 records\n"
        "    by default with truncation metadata. Use --limit N for a larger slice\n"
        "    or --no-limit only when you truly need the complete JSON payload.\n"
        "\n"
        "  Cylinder-focused queries for large parts:\n"
        "    agentcad measure v1_label/output.step --cylinders-only\n"
        "    agentcad measure v1_label/output.step --cylinders-only --diameter 12 --axis +z\n"
        "    Use reported axis labels (+x/+y/+z/other) for axis filters;\n"
        "    cylindrical feature axes are canonicalized to those labels.\n"
        "\n"
        "  Relationship to inspect:\n"
        "    measure answers dimensional questions. inspect answers topology and\n"
        "    edit-addressability questions: shell closure, free edges, validity,\n"
        "    and stable-within-shape face/edge IDs via --ids or --summary.\n"
    ),
    "check-spec": (
        "Spec checks:\n"
        "  Use check-spec when the question is whether a model satisfies an\n"
        "  explicit feature checklist from the prompt or drawing.\n"
        "\n"
        "  Workflow:\n"
        "    1. Before modeling, write measurable requirements into spec.json.\n"
        "    2. Build the model normally.\n"
        "    3. Run `agentcad check-spec output.step spec.json` before marking done.\n"
        "    4. Revise the CAD if any row is missing or failed.\n"
        "\n"
        "  Example spec:\n"
        "    {\n"
        "      \"features\": [\n"
        "        {\"name\":\"bolt_holes\", \"type\":\"cylinder\", \"diameter_mm\":12, \"count\":6},\n"
        "        {\"name\":\"center_bore\", \"type\":\"cylinder\", \"diameter_mm\":50, \"count\":1}\n"
        "      ]\n"
        "    }\n"
        "\n"
        "  Supported feature type in this slice:\n"
        "    cylinder — compares diameter_mm and count against measure's neutral\n"
        "               cylindrical feature buckets. Optional fields: axis,\n"
        "               diameter_tolerance_mm, count_tolerance.\n"
        "               If you specify axis, copy it from measure's\n"
        "               cylindrical_features[].axis field, not feature_summary.\n"
        "\n"
        "  Output fields:\n"
        "    status                 success means the comparison ran, even when\n"
        "                           the CAD fails the spec. Read passed for the\n"
        "                           actual check result.\n"
        "    passed                 True only when every spec row matched within tolerance.\n"
        "    matched_features       Rows with a matching measured diameter bucket.\n"
        "    missing_features       Rows with no measured bucket within diameter/axis tolerance.\n"
        "    total_abs_count_error  Sum of absolute count errors; missing rows count as\n"
        "                           the full expected count.\n"
        "    validity               Shape validity summary derived from measured metrics.\n"
        "    metrics                Same aggregate metrics returned by measure.\n"
        "\n"
        "  check-spec is stricter than eyeballing measure output: it does not\n"
        "  nearest-match unrelated diameters, and it reports missing features as\n"
        "  missing instead of pretending a different bucket satisfies the spec.\n"
    ),
    "helpers": (
        "agentcad.helpers — Geometry primitives and positioning:\n"
        "  from agentcad.helpers import loft_sections, tapered_sweep, naca_wire, mirror_fuse, translate, rotate, annular_boss, raise_annulus, involute_gear_profile\n"
        "\n"
        "  loft_sections(sections, smooth=True)\n"
        "    Loft through a list of TopoDS_Wire sections to produce a solid.\n"
        "    sections: list of TopoDS_Wire (minimum 2). smooth: True for smooth, False for ruled.\n"
        "\n"
        "  tapered_sweep(spine, radii)\n"
        "    Loft circular sections along a spine with varying radii.\n"
        "    spine: list of (x,y,z) tuples. radii: list of floats, one per point.\n"
        "\n"
        "  naca_wire(y, le_x, te_x, thickness, profile='0012')\n"
        "    Generate a closed NACA 4-digit airfoil wire at a given Y position.\n"
        "    thickness: max thickness as percentage of chord (e.g. 12).\n"
        "\n"
        "  mirror_fuse(shape, plane='XZ')\n"
        "    Mirror a shape about a coordinate plane (XZ, YZ, or XY) and fuse.\n"
        "\n"
        "  translate(shape, x, y, z)\n"
        "    Translate a TopoDS_Shape by (x, y, z). Returns a new shape.\n"
        "\n"
        "  rotate(shape, axis, angle_deg)\n"
        "    Rotate a TopoDS_Shape around 'X', 'Y', or 'Z' axis through the origin.\n"
        "    angle_deg: rotation in degrees. Follows right-hand rule:\n"
        "    positive angle = counterclockwise when looking from positive axis toward origin.\n"
        "    E.g. positive Y rotation moves +Z toward +X.\n"
        "    Returns a new shape.\n"
        "\n"
        "  bbox_point(shape, x='center', y='center', z='center')\n"
        "    Query a point on a shape's bounding box. Each axis: 'min', 'center', or 'max'.\n"
        "    Returns a (x, y, z) tuple. Use to find corners, edges, or centers.\n"
        "\n"
        "  place_at(shape, from_pt, to_pt)\n"
        "    Translate shape so from_pt moves to to_pt. Both are (x,y,z) tuples.\n"
        "    Combines with bbox_point for declarative positioning.\n"
        "\n"
        "  assemble(*shapes)\n"
        "    Combine TopoDS_Shape objects into a compound ready for show_object().\n"
        "    Eliminates the Shape.cast / makeCompound / newObject ceremony.\n"
        "    Usage: show_object(assemble(part1, part2, part3))\n"
        "\n"
        "  annular_boss(center, inner_radius, outer_radius, height, z_min=0)\n"
        "    Create a raised annular land as a raw TopoDS_Shape. You can pass\n"
        "    inner_diameter / outer_diameter instead of radii.\n"
        "\n"
        "  raise_annulus(source, *, center=(x,y), inner_diameter=74,\n"
        "                outer_diameter=134.2, height=10, z=0)\n"
        "    Add an annular boss to a STEP path or raw shape. Returns a compound\n"
        "    by default so fragile imported STEPs don't require a boolean fuse;\n"
        "    pass fuse=True to try a union with compound fallback.\n"
        "\n"
        "  ellipse_wire(x_radius, y_radius, center=(0,0,0), normal=(0,0,1))\n"
        "    Create an elliptical wire. x_radius along local X, y_radius along local Y.\n"
        "    Auto-swaps if y > x (OCP requires major >= minor). Returns TopoDS_Wire.\n"
        "\n"
        "  spline_wire(points, closed=True)\n"
        "    Create a smooth spline wire through 3D points (minimum 3).\n"
        "    points: list of (x,y,z) tuples. closed: close the wire. Returns TopoDS_Wire.\n"
        "\n"
        "  polygon_wire(points, closed=True)\n"
        "    Create a wire from straight line segments between points (minimum 3).\n"
        "    points: list of (x,y,z) tuples. closed: close the wire. Returns TopoDS_Wire.\n"
        "\n"
        "  rounded_rect_wire(width, height, fillet_radius, center=(0,0,0), normal=(0,0,1))\n"
        "    Create a rectangle wire with rounded corners.\n"
        "    fillet_radius: corner radius (0 for sharp). Must be <= min(width,height)/2.\n"
        "    Returns TopoDS_Wire.\n"
        "\n"
        "  elliptical_sweep(spine, x_radii, y_radii)\n"
        "    Loft elliptical sections along a spine with varying X and Y radii.\n"
        "    Same API shape as tapered_sweep but with independent X/Y control.\n"
        "    spine: list of (x,y,z). x_radii, y_radii: list of floats, one per point.\n"
        "\n"
        "  involute_gear_profile(module, teeth, pressure_angle=20.0)\n"
        "    Generate a closed involute spur gear profile wire centered at origin in XY plane.\n"
        "    module: tooth size (pitch diameter / teeth). teeth: number of teeth (min 6).\n"
        "    pressure_angle: in degrees (default 20). Returns TopoDS_Wire.\n"
        "    ⚠ KNOWN BROKEN — issue #68: emits a self-intersecting wire that\n"
        "    extrudes to an invalid solid. For gears today, use a cylinder blank\n"
        "    with manual tooth cuts (see `docs examples` Example 3).\n"
        "\n"
        "  Limitations:\n"
        "    tapered_sweep works best with smooth spines. Sharp direction changes\n"
        "    cause cross-section flipping and surface distortion. Workaround:\n"
        "    split the spine into smooth segments, sweep each separately, and\n"
        "    combine with cq.Compound.makeCompound().\n"
        "\n"
        "  Type conversion patterns (helper output -> show_object):\n"
        "    Preferred: use assemble() to combine shapes for show_object:\n"
        "      show_object(assemble(part1, part2, part3))\n"
        "\n"
        "    Manual approach (assemble does this internally):\n"
        "      shape = cq.Shape.cast(topo_shape)         # wrap single shape\n"
        "      wp = cq.Workplane('XY').newObject([shape]) # wrap for show_object\n"
        "      show_object(wp)\n"
        "\n"
        "    Note: multiple show_object() calls emit a `parts` array (one entry\n"
        "    per call) plus a compound STEP. See 'agentcad docs parts'.\n"
    ),
    "parametric": (
        "Parametric scripts:\n"
        "  Declare parameters as top-level assignments in your script:\n"
        "    length = 50.0\n"
        "    width = 20.0\n"
        "    result = cq.Workplane('XY').box(length, width, 10)\n"
        "    show_object(result)\n"
        "\n"
        "  Override with --params on agentcad run:\n"
        "    agentcad run script.py --output v2 --params length=100,width=30\n"
        "\n"
        "  Supported types: int, float, str, bool.\n"
        "  Type coercion: bool ('true'/'false') > int > float > string.\n"
        "  key=value pairs are comma-separated.\n"
        "\n"
        "  Parameters are auto-detected from top-level assignments.\n"
        "  Nested assignments (inside functions, loops) are not parameters.\n"
        "  The preamble imports do not create spurious parameters.\n"
        "\n"
        "  Errors:\n"
        "    Unknown parameter name → status 'error' with available names.\n"
        "    Bad format (no '=') → status 'error'.\n"
        "    Both return immediately without consuming a version number.\n"
        "\n"
        "  Params are recorded in JSON output and meta.json.\n"
        "  agentcad diff shows parameter changes between versions.\n"
    ),
    "patterns": (
        "CadQuery patterns — avoiding common footguns:\n"
        "\n"
        "  Build at origin, then position:\n"
        "    Create geometry at the origin, then use translate() or rotate()\n"
        "    to place it. Don't try to build at the target location.\n"
        "      part = cq.Workplane('XY').box(10, 20, 5).val().wrapped\n"
        "      placed = translate(part, 50, 0, 0)\n"
        "\n"
        "  Revolve axis:\n"
        "    .revolve() axis is relative to the current workplane origin.\n"
        "    .move() shifts the sketch pen without moving the origin.\n"
        "    Common trap: revolving after .move() produces offset geometry.\n"
        "    Fix: use .transformed(offset=(...)) to shift the workplane origin\n"
        "    before sketching, or build at origin and translate() after.\n"
        "\n"
        "  Compound vs Union:\n"
        "    cq.Compound.makeCompound() — spatial grouping for assemblies.\n"
        "      Parts remain separate solids. Use for multi-part designs.\n"
        "    .union() — boolean fuse into a single solid.\n"
        "      Use when you want one merged body (e.g. boss on a plate).\n"
        "    Multiple show_object() calls produce a `parts` array + compound STEP.\n"
        "\n"
        "  Workplane positioning:\n"
        "    .transformed(offset=(x,y,z)) — shift workplane origin in local coords.\n"
        "    .workplane(offset=N) — stack along the workplane normal.\n"
        "    .center(x, y) — move sketch pen relative to workplane origin.\n"
        "    .move(x, y) — move sketch pen (does NOT move workplane origin).\n"
        "\n"
        "  Angled positioning (e.g. tilted arm):\n"
        "    Build the part at the origin along Z, rotate to the desired angle,\n"
        "    then translate to the attachment point.\n"
        "      arm = cq.Workplane('XY').circle(5).extrude(120).val().wrapped\n"
        "      tilted = rotate(arm, 'Y', 30)      # 30° from vertical\n"
        "      placed = translate(tilted, 0, 0, 8) # attach to base top\n"
        "\n"
        "  Assembly positioning (bbox_point + place_at):\n"
        "    Instead of manual coordinate math, use bbox_point to find attachment\n"
        "    points and place_at to snap parts together:\n"
        "      base = cq.Workplane('XY').box(100, 100, 10).val().wrapped\n"
        "      leg = cq.Workplane('XY').box(5, 5, 80).val().wrapped\n"
        "      leg = place_at(leg,\n"
        "          from_pt=bbox_point(leg, 'center', 'center', 'min'),\n"
        "          to_pt=bbox_point(base, 'max', 'max', 'max'))\n"
        "      show_object(assemble(base, leg))\n"
        "\n"
        "    bbox_point axes: 'min', 'center', 'max' for each of x, y, z.\n"
        "    Common combos:\n"
        "      bbox_point(s, 'center', 'center', 'max')  # top center\n"
        "      bbox_point(s, 'center', 'center', 'min')  # bottom center\n"
        "      bbox_point(s, 'min', 'min', 'min')        # bottom-left-back corner\n"
        "\n"
        "  twistExtrude performance:\n"
        "    For profiles with >100 points, use polyline() instead of spline().\n"
        "    The spline kernel scales poorly — 1000-point spline + twistExtrude\n"
        "    can take 5+ minutes. polyline completes in under a minute.\n"
        "\n"
        "  Subtractive construction (cut from blank):\n"
        "    For complex profiles (gears, splines, keyways), build a solid blank\n"
        "    (cylinder, box) and cut the negative space out with BRepAlgoAPI_Cut.\n"
        "    This is more robust than building the profile up additively because:\n"
        "      - The blank already has correct outward-facing normals.\n"
        "      - Boolean subtraction preserves normal orientation automatically.\n"
        "      - Fewer wire closure issues — the cutter shape is typically simpler.\n"
        "    Example: spur gear — start with a tip-radius cylinder, cut 20 rotated\n"
        "    gap solids out of it, rather than extruding 20 tooth prisms.\n"
        "      from OCP.BRepAlgoAPI import BRepAlgoAPI_Cut\n"
        "      blank = BRepPrimAPI_MakeCylinder(tip_r, thickness).Shape()\n"
        "      for i in range(num_teeth):\n"
        "          gap_i = <rotated gap cutter solid>\n"
        "          blank = BRepAlgoAPI_Cut(blank, gap_i).Shape()\n"
        "\n"
        "  Wire winding direction:\n"
        "    When building wires manually, winding order determines face normals:\n"
        "      - CCW in XY plane → face normal points +Z (outward for top faces).\n"
        "      - CW in XY plane → face normal points −Z (inverted).\n"
        "    Extruding a CW wire produces a solid with inward normals and negative\n"
        "    volume. The shape will render but is_valid may be false.\n"
        "    Diagnosis: if agentcad run reports negative volume, check winding order.\n"
        "    Fix: reverse the wire, or use subtractive construction (see above).\n"
        "\n"
        "  Mixed edge type wires:\n"
        "    For profiles that combine straight lines, arcs, and splines, build\n"
        "    the wire from individual edges using BRepBuilderAPI_MakeWire:\n"
        "      from OCP.BRepBuilderAPI import BRepBuilderAPI_MakeWire, BRepBuilderAPI_MakeEdge\n"
        "      from OCP.gp import gp_Pnt\n"
        "      wb = BRepBuilderAPI_MakeWire()\n"
        "      wb.Add(BRepBuilderAPI_MakeEdge(gp_Pnt(0,0,0), gp_Pnt(10,0,0)).Edge())\n"
        "      wb.Add(BRepBuilderAPI_MakeEdge(<arc or spline curve>).Edge())\n"
        "      wire = wb.Wire()\n"
        "    Each edge's endpoint must match the next edge's start within tolerance\n"
        "    (~1e-7mm). Print the endpoint coordinates to debug closure failures.\n"
        "    For circular arcs, use Geom_Circle + GC_MakeArcOfCircle.\n"
        "    For splines through points, use GeomAPI_PointsToBSpline.\n"
    ),
    "inspect": (
        "Inspecting shape topology:\n"
        "  agentcad inspect <step_file> [--ids] [--summary] [--limit N|--no-limit]\n"
        "\n"
        "  Reports the internal topology of a STEP file:\n"
        "    file             Source file path\n"
        "    format_detected / extension / size_bytes\n"
        "                     Source file metadata\n"
        "    solid_count      Number of solid bodies\n"
        "    shell_count      Number of shells\n"
        "    shells           Per-shell details (closed/open, face count)\n"
        "    face_count       Total unique faces\n"
        "    face_orientations  Forward vs reversed face counts\n"
        "    edge_count       Total unique edges\n"
        "    free_edge_count  Edges belonging to fewer than 2 faces (holes)\n"
        "    is_valid         BRepCheck validity\n"
        "    validity_errors  BRepCheck error classes (only when is_valid=false)\n"
        "    next_actions     Agent-facing follow-up commands\n"
        "    more_at          Docs pointer\n"
        "    notes            Contextual clarifications when output fields look\n"
        "                     surprising but are not necessarily defects\n"
        "    solids / faces / edges\n"
        "                     Per-feature ID lists emitted only with --ids\n"
        "    summary          Compact face/edge clusters emitted only with --summary:\n"
        "                     face_count, edge_count, face_clusters,\n"
        "                     edge_clusters, id_truncation?\n"
        "                     Cluster fields include ids, count, axis?, radius?,\n"
        "                     diameter?, area_mean/min/max?, length_mean?,\n"
        "                     surface_type?, curve_type?, ids_total?,\n"
        "                     ids_omitted?, ids_truncated?.\n"
        "    truncation       Present when --ids or --summary output is capped by\n"
        "                     --limit/default limits\n"
        "\n"
        "  Use this to debug geometry issues:\n"
        "    - Hollow shapes: check shell closed status and free edges\n"
        "    - Inverted normals: check face orientation balance\n"
        "    - Invalid geometry: check is_valid field\n"
        "\n"
        "  Edit-risk guidance (only emitted for risky inputs):\n"
        "    edit_risk            'high' or 'medium'\n"
        "    risk_reasons         why (invalid topology, large topology,\n"
        "                         many free edges, named BRepCheck errors)\n"
        "    recommended_workflow command-oriented steps to take instead\n"
        "\n"
        "    HIGH means the import is invalid AND large/complex (the\n"
        "    timeout-prone case): do NOT start with load_step() + boolean/\n"
        "    fillet edits — prefer additive/proxy rebuilds and targeted\n"
        "    measure queries. MEDIUM means recoverable (invalid-but-small:\n"
        "    heal then edit; or large-but-valid: editable but slow). When\n"
        "    no edit_risk field is present, the input is low-risk.\n"
        "\n"
        "  For dimensional questions, run:\n"
        "    agentcad measure <step_file>\n"
        "\n"
        "  Addressable IDs:\n"
        "    agentcad inspect <step_file> --ids\n"
        "    Emits solids[], faces[], and edges[] for targeted edits. Lists are\n"
        "    capped at 100 records by default with truncation metadata. Use\n"
        "    --limit N for a larger slice or --no-limit only when you need every\n"
        "    face and edge in the JSON response.\n"
        "    agentcad inspect <step_file> --summary emits the summary field with\n"
        "    compact clusters and representative face/edge IDs for smaller\n"
        "    targeting payloads.\n"
    ),
    "daemon": (
        "Daemon (auto-managed background worker):\n"
        "  The first 'agentcad run' in a venv spawns a background daemon\n"
        "  that keeps CadQuery/OCP loaded in memory. Subsequent runs route\n"
        "  through it at ~0.1s instead of paying the OCP import cost.\n"
        "  Each venv gets its own daemon (per-venv socket path). After a pip\n"
        "  upgrade, a running daemon continues using the version loaded at\n"
        "  startup. Routed commands and daemon status warn on a mismatch;\n"
        "  run 'agentcad daemon restart' to load the installed version.\n"
        "\n"
        "  Agents do not need to start, stop, or check the daemon. It just\n"
        "  works. The commands below exist for diagnostics:\n"
        "\n"
        "  agentcad daemon status  — Check if a daemon is running for this\n"
        "                            venv; reports pid and version.\n"
        "  agentcad daemon stop    — Force-stop the daemon (frees memory).\n"
        "                            Next 'agentcad run' will spawn a new one.\n"
        "  agentcad daemon restart — Reload the installed agentcad version\n"
        "                            after an upgrade warning.\n"
        "\n"
        "  agentcad run --no-daemon  — One-off opt-out for a single run\n"
        "                              (does not spawn or route).\n"
        "\n"
        "  Platform note (Windows):\n"
        "    The daemon requires POSIX primitives (os.fork, AF_UNIX,\n"
        "    os.getuid) and is disabled on Windows. Every command runs\n"
        "    directly — output is identical to a POSIX run with --no-daemon,\n"
        "    but each invocation pays the full OCP import cost (~seconds)\n"
        "    instead of the routed ~0.1s. 'agentcad daemon' subcommands\n"
        "    return {\"status\": \"unsupported\"} on Windows instead of\n"
        "    attempting to spawn.\n"
    ),
    "parts": (
        "Per-part design workflow:\n"
        "  Every show_object() call becomes a part in the run output. Each\n"
        "  part gets a string id. Name and color are optional display metadata.\n"
        "    show_object(deck, id=\"main_deck\", name=\"Deck\", options={\"color\": \"gray\"})\n"
        "    show_object(pin, name=\"pin\", options={\"color\": \"blue\"})\n"
        "    show_object(frame)                         # unnamed is fine\n"
        "    show_object(rib, id=\"rib\", options={\"part_of\": \"frame\", \"group_color\": \"steelblue\"})\n"
        "\n"
        "  ID policy:\n"
        "    - explicit id= or options.id wins, normalized as a slug (id_source=\"explicit\")\n"
        "    - otherwise a unique slug is derived from name (id_source=\"name\")\n"
        "    - anonymous parts get part_<index> (id_source=\"generated\")\n"
        "      and should be treated as version-local handles.\n"
        "\n"
        "  Available colors: red, green, blue, yellow, orange, purple,\n"
        "    gray/grey, white, black, brown, pink, teal, gold, silver, cyan,\n"
        "    steelblue, coral, forestgreen, or #RRGGBB.\n"
        "  Group color: set options.group_color with options.part_of to give\n"
        "    every uncolored member of that lightweight group the same color.\n"
        "\n"
        "  Output shape (`parts` array, always emitted):\n"
        "    {\n"
        "      \"id\": \"main_deck\",        # stable part handle\n"
        "      \"id_source\": \"explicit\",  # explicit | name | generated\n"
        "      \"name\": \"Deck\",            # optional, omitted if not set\n"
        "      \"color\": \"gray\",           # optional, omitted if not set\n"
        "      \"part_of\": \"frame\",       # optional lightweight group id\n"
        "      \"metrics\": {\"volume\": ..., \"center_of_mass\": ..., \"face_count\": ..., \"is_valid\": ...},\n"
        "      \"preview\": \"v1_label/parts/deck.png\"\n"
        "    }\n"
        "    groups[] contains lightweight group records:\n"
        "      {\"id\": \"frame\", \"name\": \"frame\", \"color\": \"steelblue\", \"part_ids\": [\"rib\", ...]}\n"
        "\n"
        "  Per-part preview files:\n"
        "    Each part gets an iso PNG under <version>/parts/. Filename is the\n"
        "    resolved part id. Skipped when --no-preview is passed (metrics\n"
        "    still computed).\n"
        "\n"
        "  Diffing parts:\n"
        "    'agentcad diff' reports per-part changes. New parts-schema\n"
        "    versions are matched by id so display names can change.\n"
        "\n"
        "  Reading parts from existing versions:\n"
        "    agentcad parts list v3\n"
        "    agentcad parts show v3 main_deck\n"
        "    agentcad parts view v3 --isolate main_deck --ghost-rest --focus main_deck\n"
        "    agentcad parts view v3 --isolate-group frame --ghost-rest --focus-group frame\n"
        "    agentcad parts view v3 --label \"Frame check\" --note \"Inspect the gussets\" \\\n"
        "      --isolate-group frame --ghost-rest --focus-group frame\n"
        "    These read the same <version>/meta.json snapshot that powers\n"
        "    viewer.html, so model outputs, viewer state, and parts stay tied\n"
        "    to the same run version.\n"
        "    parts view writes a temporary HTML review artifact backed by\n"
        "    viewer_glb, so agents can hand humans a prepared hide/isolate/ghost\n"
        "    state without live browser control. The human can change the viewer\n"
        "    freely; those browser changes are not saved, and AgentCAD does not\n"
        "    keep a saved-views catalog yet.\n"
        "    The JSON response includes handoff.url, handoff.message,\n"
        "    temporary=true, and persisted=false for agent-to-human handoff.\n"
        "    Group-level view commands expand to the member part ids and the\n"
        "    viewer also exposes group hide/isolate controls.\n"
        "\n"
        "  STEP output is still a single compound file; parts[] is the data\n"
        "  channel. Top-level \"metrics\" covers the compound; part-level\n"
        "  metrics cover each shape individually.\n"
    ),
    "workflow": (
        "Typical workflow:\n"
        "  1. agentcad init --name myproject\n"
        "  2. Write a build123d or CadQuery script (script.py) with show_object().\n"
        "  3. agentcad run script.py --output label [--render iso] [--export stl,glb]\n"
        "  4. agentcad measure v1_label/output.step — check dimensions and feature sizes.\n"
        "  5. agentcad check-spec v1_label/output.step spec.json — compare against intent.\n"
        "  6. agentcad render v1_label/output.step --view front,top --zoom 1.5\n"
        "  7. agentcad export v1_label/output.step --format stl,glb\n"
        "  8. agentcad context — review project state.\n"
        "  9. agentcad diff 1 2 — compare versions.\n"
    ),
    "feedback": (
        "Feedback:\n"
        "  agentcad feedback \"your observation\"\n"
        "\n"
        "  Hit friction? Confused by an error? Wish a helper existed? Send it —\n"
        "  any observation, mid-task, no permission needed. Your message is\n"
        "  bundled with the recent session log and goes straight to the agentcad\n"
        "  team. Casual, partial, just-a-thought messages are exactly the signal\n"
        "  we want.\n"
        "\n"
        "  --local-only     Save the bundle locally without sending.\n"
        "  --max-entries N  Session log entries to include (default 10).\n"
    ),
    "mcp": (
        "MCP integration — native agent tools:\n"
        "  agentcad ships with an MCP (Model Context Protocol) server so agents\n"
        "  can call commands as native tools instead of shelling out to the CLI.\n"
        "\n"
        "  Setup:\n"
        "    1. Install the MCP extra:\n"
        "       pip install agentcad[mcp]\n"
        "\n"
        "    2. Add to your .mcp.json (Claude Code, Cursor, Windsurf, etc.):\n"
        '       {"agentcad": {"command": "python", "args": ["-m", "agentcad.mcp"]}}\n'
        "\n"
        "  Available tools:\n"
        "    run       Execute a build123d or CadQuery script, produce STEP + metrics\n"
        "    render    Render PNG views of a STEP file\n"
        "    export    Export STEP to mesh formats (stl, glb, obj)\n"
        "    measure   Dimensional report (overall metrics and feature sizes)\n"
        "    inspect   Topology report (solids, shells, faces, validity)\n"
        "    docs      Show documentation (this command)\n"
        "    context   Project state (versions, current)\n"
        "    diff      Compare two versions\n"
        "    view      Open GLB/STEP in browser\n"
        "\n"
        "  All tools accept a 'cwd' parameter pointing to the project directory.\n"
        "  Responses are the same JSON as the CLI — same schema, same fields.\n"
        "\n"
        "  Why MCP over CLI?\n"
        "    - No shell parsing — structured parameters in, structured JSON out.\n"
        "    - Persistent process — CadQuery stays loaded, no 3-5s cold start.\n"
        "    - Native tool UI — agents see typed parameters, not raw argv.\n"
    ),
    "runtimes": (
        "Choosing a runtime — cadquery vs build123d:\n"
        "  agentcad runs scripts on one of two CAD engines. Both compile to the\n"
        "  same OCP (OpenCascade) kernel — the geometry and metrics are identical;\n"
        "  only the script-writing API differs.\n"
        "\n"
        "  Same shape, both ways:\n"
        "\n"
        "    cadquery:\n"
        "      box = cq.Workplane('XY').box(10, 20, 5)\n"
        "      show_object(box)\n"
        "\n"
        "    build123d:\n"
        "      box = Box(10, 20, 5)\n"
        "      show_object(box)\n"
        "\n"
        "  When to pick which:\n"
        "    build123d  Recommended for new projects. Direct primitives, Python\n"
        "               operators for booleans (-, +, &), better composition for\n"
        "               complex assemblies. The migration target.\n"
        "    cadquery   Legacy supported runtime. Workplane-fluent API. Pick this if you're\n"
        "               porting existing scripts or already comfortable with it.\n"
        "\n"
        "  How dispatch works (highest precedence to lowest):\n"
        "    1. Explicit `--runtime` flag on `agentcad run` — beats everything.\n"
        "    2. Script imports — `import cadquery` → cq runner; `from build123d`\n"
        "       → b3d runner. Beats the project manifest.\n"
        "    3. Project manifest (agentcad.json `runtime` key, set via\n"
        "       `agentcad init --runtime build123d`).\n"
        "    4. Global default: build123d.\n"
        "\n"
        "  Switching runtimes mid-project:\n"
        "    Edit `agentcad.json` and set `\"runtime\": \"build123d\"`, or pass\n"
        "    `--runtime build123d` per-run. Existing version directories keep\n"
        "    working — each meta.json records the runtime it was produced with.\n"
        "\n"
        "  See `agentcad docs preamble`, `quickstart`, `examples`, `patterns`,\n"
        "  `helpers` for runtime-specific guidance — those topics auto-route to\n"
        "  the project's runtime, or pass `--runtime build123d` to override.\n"
    ),
    "build123d": (
        "build123d runtime — overview pointer:\n"
        "  build123d is the recommended runtime for new agentcad projects. This\n"
        "  topic is just a pointer; the real content lives in the runtime-aware\n"
        "  topics below (each shows build123d content when the project's runtime\n"
        "  is build123d, or when you pass `--runtime build123d`).\n"
        "\n"
        "  Start here:\n"
        "    agentcad docs runtimes      — cadquery vs build123d, when to pick\n"
        "    agentcad docs quickstart    — first script (build123d when applicable)\n"
        "    agentcad docs preamble      — pre-injected names in scripts\n"
        "    agentcad docs patterns      — booleans, edges, fillets, sketches\n"
        "    agentcad docs helpers       — using agentcad.helpers from build123d\n"
        "    agentcad docs examples      — worked examples (plate, bracket, gear)\n"
        "    agentcad docs parts         — current per-part limitation (issue #69)\n"
        "\n"
        "  To make a new project default to build123d:\n"
        "    agentcad init --name myproject --runtime build123d\n"
        "\n"
        "  To get build123d docs without a project pinned to it:\n"
        "    agentcad docs <section> --runtime build123d\n"
    ),
    "editing": (
        "Editing existing CAD files — the M60 edit journey:\n"
        "\n"
        "  Workflow: agent receives a STEP/BREP, makes specific changes,\n"
        "  and the tool tracks edits as versioned diffs.\n"
        "\n"
        "  1. Import the file (becomes v1 with provenance):\n"
        "       agentcad import vendor.step --init\n"
        "\n"
        "  2. Inspect with --ids to see addressable faces / edges:\n"
        "       agentcad inspect v1_vendor/output.step --ids\n"
        "       # JSON now includes solids[], faces[{id,area,centroid,normal,bbox}],\n"
        "       # edges[{id,length,endpoints}]. Pick the ID(s) you want to edit.\n"
        "\n"
        "  3. Edit using the build123d edit-journey helpers:\n"
        "       from build123d import *\n"
        "       base = load_step('v1_vendor/output.step')\n"
        "       top_face = pick_face(base, 7)            # face ID from inspect\n"
        "       result = base.fillet(0.5, top_face.edges())\n"
        "       show_object(result)\n"
        "\n"
        "  4. Run — auto-diffs against the imported baseline:\n"
        "       agentcad run edit.py --output filleted\n"
        "\n"
        "  ID stability: face/edge IDs are 1-indexed and stable WITHIN a shape\n"
        "  (same shape, same IDs every inspect). They are NOT stable across\n"
        "  edits — even a small fillet can renumber faces. Re-run\n"
        "  `inspect --ids` after each edit to get current IDs.\n"
        "\n"
        "  Helpers shipped with the edit pipeline (build123d topology helpers\n"
        "  plus runtime-neutral annular helpers):\n"
        "    load_step(path) -> Part         load a STEP/STP/BREP as a Part\n"
        "    load_step_shape(path) -> TopoDS  raw OCCT shape (escape hatch)\n"
        "    pick_face(shape, id) -> Face    look up by ID from inspect --ids\n"
        "    pick_edge(shape, id) -> Edge    look up by ID from inspect --ids\n"
        "    fillet_edges(shape, ids, r)     fillet edges by ID, radius r\n"
        "    chamfer_edges(shape, ids, d)    chamfer edges by ID, distance d\n"
        "    shell_faces(shape, ids, t)      hollow shape, opening face IDs;\n"
        "                                    negative t = inward (typical wall)\n"
        "                                    positive t = outward (rare)\n"
        "    split_by_plane(shape, plane)    cut shape with infinite plane;\n"
        "                                    returns (below, above) tuple.\n"
        "                                    plane: 'XY' / 'XZ' / 'YZ' or a\n"
        "                                    build123d Plane (e.g. Plane.XY.offset(5)).\n"
        "    cut_pocket(shape, face_id, profile, depth)\n"
        "                                    cut a pocket on the picked face by\n"
        "                                    extruding profile inward by depth.\n"
        "                                    profile is a build123d Sketch / Face.\n"
        "    boss(shape, face_id, profile, height)\n"
        "                                    add a raised feature on the picked\n"
        "                                    face by extruding profile outward.\n"
        "                                    Same shape as cut_pocket but adds\n"
        "                                    instead of subtracts.\n"
        "    annular_boss(center, inner_radius, outer_radius, height, z_min=0)\n"
        "                                    create only a raised annular land;\n"
        "                                    accepts diameter kwargs too.\n"
        "    raise_annulus(source, *, center, inner_diameter, outer_diameter, height, z=0)\n"
        "                                    add a raised annular land to a STEP\n"
        "                                    path or raw shape. Returns a compound\n"
        "                                    by default, avoiding fragile fuses.\n"
        "    Example feature ops:\n"
        "      profile = Sketch() + Circle(radius=3)\n"
        "      result = cut_pocket(base, face_id=7, profile=profile, depth=4)\n"
        "      result = boss(base, face_id=7, profile=profile, height=4)\n"
        "      raw = load_step_shape('v1_vendor/output.step')\n"
        "      result = raise_annulus(raw, center=(-105, -30),\n"
        "                            inner_diameter=74, outer_diameter=134.2,\n"
        "                            height=10, z=0)\n"
        "      show_object(Compound(result))\n"
        "    `ids` accepts a single int or a list. Out-of-range raises\n"
        "    ValueError pointing back at `inspect --ids`.\n"
        "    Limitation: shell_faces can't open a face that has an inner\n"
        "    loop (e.g. a through-hole pierces it). Pick a different face,\n"
        "    or plug the hole before shelling and re-cut afterward.\n"
        "\n"
        "  CadQuery users: most topology-ID helpers above are build123d-only;\n"
        "  annular_boss and raise_annulus are runtime-neutral raw-shape helpers.\n"
        "  For other edits, use the CadQuery-native imported STEP path:\n"
        "    from cadquery import importers\n"
        "    base = importers.importStep('v1_vendor/output.step')\n"
        "    # then native CadQuery selectors (faces('>Z') etc.)\n"
        "  Calling pick_face / pick_edge / load_step in a CadQuery script\n"
        "  fails fast with a validation error pointing at this fallback.\n"
    ),
}


BUILD123D_OVERLAY = {
    "parts": (
        "Per-part design workflow (build123d runtime):\n"
        "  Multiple show_object() calls produce a `parts` array — same shape\n"
        "  as the cadquery runtime. Each show_object() call becomes one part.\n"
        "  show_assembly() captures an intentional multi-body result as one\n"
        "  assembly entry with compound-level metrics. STEP export\n"
        "  still writes a single compound file that contains every part.\n"
        "\n"
        "    base = Box(100, 100, 5)\n"
        "    leg  = Box(5, 5, 50).translate((40, 40, 27.5))\n"
        "    show_object(base, name=\"base\", options={\"color\": \"gray\"})\n"
        "    show_object(leg,  id=\"front_leg\", name=\"leg\", options={\"color\": \"steelblue\"})\n"
        "\n"
        "  ID policy:\n"
        "    - explicit id= or options.id wins, normalized as a slug (id_source=\"explicit\")\n"
        "    - otherwise a unique slug is derived from name (id_source=\"name\")\n"
        "    - anonymous parts get part_<index> (id_source=\"generated\")\n"
        "      and should be treated as version-local handles.\n"
        "\n"
        "    show_object(leg, options={\"id\": \"front_leg\", \"name\": \"leg\", \"color\": \"steelblue\"})\n"
        "\n"
        "  Run output includes:\n"
        "    parts[]      one entry per show_object() call. Each has:\n"
        "                   id          string handle from explicit id, name slug, or part_<index>\n"
        "                   id_source   explicit | name | generated\n"
        "                   name        from name= kwarg/options, or null\n"
        "                   color       from options.color, or null\n"
        "                   part_of     optional lightweight group id\n"
        "                   metrics     bbox/volume/dimensions/etc. (per-part)\n"
        "                   preview     PNG path (when preview is on)\n"
        "    groups[]     lightweight groups derived from options.part_of;\n"
        "                 options.group_color colors uncolored group members.\n"
        "    metrics      compound metrics for the assembly\n"
        "    output_type  single_part | assembly (capture intent; not a solid count)\n"
        "\n"
        "  Available colors: red, green, blue, yellow, orange, purple,\n"
        "    gray/grey, white, black, brown, pink, teal, gold, silver, cyan,\n"
        "    steelblue, coral, forestgreen, or #RRGGBB.\n"
        "\n"
        "  Single show_object(Compound(children=[...])) still works and is\n"
        "  the right call when you've built the assembly explicitly and don't\n"
        "  want per-part identity.\n"
        "  For ShapeList/list/tuple outputs you intentionally want as one\n"
        "  multi-body assembly, prefer:\n"
        "    show_assembly(result, name=\"assembly_name\")\n"
        "\n"
        "  GLB export auto-colors per-part using the colors above when set.\n"
        "  Agents can generate temporary part review viewers with:\n"
        "    agentcad parts view v3 --isolate front_leg --ghost-rest --focus front_leg\n"
        "    agentcad parts view v3 --isolate-group frame --ghost-rest --focus-group frame\n"
        "    agentcad parts view v3 --label \"Frame check\" --note \"Inspect the gussets\" \\\n"
        "      --isolate-group frame --ghost-rest --focus-group frame\n"
        "  These are handoff artifacts, not saved CAD views: users can adjust\n"
        "  the viewer in the browser, and those changes disappear when it closes.\n"
    ),
    "quickstart": (
        "Quickstart (build123d):\n"
        "  1. Initialize a project pinned to build123d:\n"
        "     agentcad init --name myproject --runtime build123d\n"
        "\n"
        "  2. Write a script. The build123d API is pre-injected — write\n"
        "     primitives directly, no imports needed:\n"
        "     box = Box(10, 20, 5)\n"
        "     show_object(box)\n"
        "\n"
        "  3. Run it:\n"
        "     agentcad run script.py --output first_box\n"
        "     The default --preview produces a 4-view composite PNG (preview.png)\n"
        "     and viewer.html; --render is only needed for extra camera angles.\n"
        "\n"
        "  Booleans use Python operators:\n"
        "     plate = Box(60, 40, 5)\n"
        "     hole  = Cylinder(radius=3, height=10)\n"
        "     show_object(plate - hole)        # subtract\n"
        "     show_object(Box(10,10,10) + Sphere(6).translate((20,0,0)))  # union\n"
        "\n"
        "  Multiple show_object() calls emit a `parts` array in the run output\n"
        "  (one entry per call, with per-part metrics + preview) plus a single\n"
        "  compound STEP file. See 'agentcad docs parts' for the full schema.\n"
    ),
    "preamble": (
        "Script preamble (pre-injected names, build123d runtime):\n"
        "  Every script executed by 'agentcad run' on the build123d engine\n"
        "  has the following names available without any import statements:\n"
        "\n"
        "  build123d (the entire public API, star-imported):\n"
        "    Box, Cylinder, Sphere, Cone, Torus, Wedge      Primitives\n"
        "    Wire, Edge, Face, Solid, Compound, Part        Topology types\n"
        "    extrude, revolve, sweep, loft, offset          Operations\n"
        "    fillet, chamfer, mirror, scale                 Modifiers\n"
        "    Plane, Axis, Vector, Location, Locations       Positioning\n"
        "    Mode, Align, Kind, Until, Select               Enums\n"
        "    BuildPart, BuildSketch, BuildLine              Builder contexts\n"
        "    (and everything else exported by `from build123d import *`)\n"
        "\n"
        "  extrude direction — extrude(sketch, amount=N) pushes the sketch\n"
        "  along its plane's +normal:\n"
        "    Plane.XY sketch → extrude towards +Z\n"
        "    Plane.XZ sketch → extrude towards +Y\n"
        "    Plane.YZ sketch → extrude towards +X\n"
        "  Pass amount=-N to flip direction. For a wedge built on Plane.YZ,\n"
        "  extrude(sketch, amount=80) gives a 0..+80 span on X; translate\n"
        "  the result by (-40, 0, 0) to center it about the origin.\n"
        "\n"
        "  show_object   Capture function. Pass a build123d Shape to surface it.\n"
        "                Each call becomes a part in the `parts` array; STEP\n"
        "                export still writes a single compound file.\n"
        "  show_assembly Capture an intentional multi-body ShapeList/list/tuple\n"
        "                as one assembly output without manually constructing\n"
        "                Compound(children=...). Run JSON reports\n"
        "                output_type=\"assembly\".\n"
        "\n"
        "  agentcad helpers (return raw OCP shapes — wrap as needed):\n"
        "    involute_gear_profile  → TopoDS_Wire   ⚠ KNOWN BROKEN — issue #68;\n"
        "                                              extrudes to invalid solid.\n"
        "                                              See `docs examples` for the\n"
        "                                              cylinder-blank workaround.\n"
        "    naca_wire              → TopoDS_Wire\n"
        "    polygon_wire           → TopoDS_Wire\n"
        "    spline_wire            → TopoDS_Wire\n"
        "    rounded_rect_wire      → TopoDS_Wire\n"
        "    ellipse_wire           → TopoDS_Wire\n"
        "    loft_sections          → TopoDS_Shape\n"
        "    tapered_sweep          → TopoDS_Shape\n"
        "    elliptical_sweep       → TopoDS_Shape\n"
        "    mirror_fuse            → TopoDS_Shape\n"
        "    annular_boss           → TopoDS_Shape\n"
        "    raise_annulus          → TopoDS_Shape/TopoDS_Compound\n"
        "    translate, rotate      → TopoDS_Shape (use build123d's .translate()/.rotate() instead)\n"
        "    place_at, bbox_point   → tuple\n"
        "    assemble               → Compound (build123d-flavored)\n"
        "\n"
        "  To use a helper that returns TopoDS_Wire in build123d, wrap it as\n"
        "  Wire(...) → Face(...) → extrude(...). Example with naca_wire:\n"
        "    wire = naca_wire(y=0, le_x=0, te_x=100, thickness=12)\n"
        "    rib  = extrude(Face(Wire(wire)), amount=5)\n"
        "    show_object(rib)\n"
        "  (Do NOT use this pattern with `involute_gear_profile` — it's\n"
        "  currently broken; see issue #68 and `docs examples` Example 3 for\n"
        "  the cylinder-blank gear recipe to use instead.)\n"
        "\n"
        "  Explicit imports remain harmless. Adding `from build123d import Box`\n"
        "  is fine and helps editors with completion.\n"
    ),
    "helpers": (
        "agentcad.helpers from a build123d script:\n"
        "  Helpers return raw OCP shapes (TopoDS_Wire, TopoDS_Shape) for\n"
        "  portability. To use them in a build123d script, wrap the OCP\n"
        "  output in the appropriate build123d type before composing.\n"
        "\n"
        "  Wires (TopoDS_Wire return) — wrap with Wire(...) then Face(...) to\n"
        "  extrude/revolve into a solid:\n"
        "    naca = naca_wire(y=0, le_x=0, te_x=100, thickness=12)\n"
        "    rib  = extrude(Face(Wire(naca)), amount=2)\n"
        "    show_object(rib)\n"
        "\n"
        "  ⚠ involute_gear_profile is currently broken (issue #68 — emits a\n"
        "  self-intersecting wire). For gears, use the cylinder-blank recipe in\n"
        "  `docs examples` Example 3 instead of the Face(Wire(...)) pattern.\n"
        "\n"
        "  Solids (TopoDS_Shape return) — wrap with Solid(...) or Part(...)\n"
        "  to reuse build123d operators on them:\n"
        "    lower = rounded_rect_wire(40, 20, 3, center=(0, 0, 0))\n"
        "    upper = rounded_rect_wire(20, 10, 2, center=(0, 0, 30))\n"
        "    lofted = loft_sections([lower, upper])\n"
        "    show_object(Solid(lofted))\n"
        "\n"
        "    spine  = [(0,0,0), (50,0,30), (100,0,40)]\n"
        "    radii  = [10, 8, 5]\n"
        "    swept  = tapered_sweep(spine, radii)\n"
        "    show_object(Solid(swept))\n"
        "\n"
        "  Imported STEP annular edit (non-fuse default):\n"
        "    land = annular_boss(center=(-105, -30), inner_diameter=74,\n"
        "                         outer_diameter=134.2, height=10, z=0)\n"
        "    show_object(Solid(land))\n"
        "\n"
        "    raw = load_step_shape('v1_vendor/output.step')\n"
        "    result = raise_annulus(raw, center=(-105, -30),\n"
        "                          inner_diameter=74, outer_diameter=134.2,\n"
        "                          height=10, z=0)\n"
        "    show_object(Compound(result))\n"
        "  raise_annulus returns a compound by default so imported STEP edits\n"
        "  don't depend on a fragile boolean fuse. Pass fuse=True to try a union.\n"
        "\n"
        "  Translate/rotate — prefer build123d's own Shape.translate()/.rotate():\n"
        "    box = Box(10, 10, 10).translate((20, 0, 0))\n"
        "    show_object(box.rotate(Axis.Z, 30))\n"
        "  agentcad.helpers' translate/rotate are also available, but they\n"
        "  return TopoDS_Shape and need wrapping — less ergonomic.\n"
        "\n"
        "  Multi-part assembly:\n"
        "    base = Box(100, 100, 5)\n"
        "    leg  = Box(5, 5, 50).translate((40, 40, 27.5))\n"
        "    show_assembly([base, leg], name=\"frame\")\n"
        "    # or: show_object(Compound(children=[base, leg]))\n"
        "    # or: assemble(base, leg) — works the same in build123d mode.\n"
    ),
    "patterns": (
        "build123d patterns — composing primitives the right way:\n"
        "\n"
        "  Boolean ops use operators. Read like algebra:\n"
        "    plate  = Box(60, 40, 5)\n"
        "    hole   = Cylinder(radius=3, height=10)\n"
        "    bracket = plate - hole              # subtract\n"
        "    fused   = Box(10, 10, 10) + Sphere(6).translate((20, 0, 0))  # union\n"
        "    overlap = Cylinder(5, 20) & Box(8, 8, 8)                      # intersect\n"
        "\n"
        "  Construct at origin, then position. Centered primitives sit at (0,0,0):\n"
        "    arm = Box(50, 4, 4).translate((25, 0, 2))   # bottom-front edge at origin\n"
        "    arm = arm.rotate(Axis.Y, 30)                # tilt around Y\n"
        "\n"
        "  Cylinders/Spheres along a non-Z axis: use the rotation= kwarg at\n"
        "  construction time, it's cleaner than rotating after:\n"
        "    horiz_rod = Cylinder(radius=4, height=50, rotation=(0, 90, 0))\n"
        "\n"
        "  Hole patterns — Locations() lets you stamp the same cut at many points:\n"
        "    plate = Box(60, 40, 5)\n"
        "    with BuildPart() as out:\n"
        "        add(plate)\n"
        "        with Locations((20,10), (-20,10), (20,-10), (-20,-10)):\n"
        "            Cylinder(radius=2.5, height=10, mode=Mode.SUBTRACT)\n"
        "    show_object(out.part)\n"
        "  (BuildPart context optional — direct algebra mode `plate - cuts` works too.)\n"
        "\n"
        "  Fillets and chamfers — pick edges with .edges(), filter, then call:\n"
        "    plate = Box(60, 40, 5)\n"
        "    plate = fillet(plate.edges().filter_by(Axis.Z), radius=4)\n"
        "    show_object(plate)\n"
        "\n"
        "  Edge selection — know what you're picking:\n"
        "    filter_by(Axis.Z) selects edges PARALLEL to the Z axis.\n"
        "    On a box those are the four vertical corner edges — great for\n"
        "    rounding the vertical corners. On a cylindrical body (Cylinder or\n"
        "    an extruded round profile), Z-parallel edges are the side seams,\n"
        "    NOT the top/bottom rims — filleting them can break the geometry.\n"
        "    For top/bottom rims on cylindrical bodies, filter by position:\n"
        "      body = Cylinder(radius=20, height=10).translate((0, 0, 5))\n"
        "      top_edges = [e for e in body.edges() if abs(e.center().Z - 10) < 1e-3]\n"
        "      body = fillet(top_edges, radius=1)\n"
        "      show_object(body)\n"
        "    If `fillet(...)` raises 'Failed creating a fillet with radius X',\n"
        "    inspect the edge selection first — the radius may be fine but\n"
        "    the wrong edges may have been picked.\n"
        "\n"
        "  Multi-part assembly without booleans:\n"
        "    base = Box(100, 100, 5)\n"
        "    leg  = Box(5, 5, 50).translate((40, 40, 27.5))\n"
        "    show_assembly([base, leg], name=\"frame\")\n"
        "\n"
        "  Complex profiles — use BuildSketch / BuildLine context, then extrude:\n"
        "    with BuildSketch() as sk:\n"
        "        Rectangle(40, 20)\n"
        "        Circle(8, mode=Mode.SUBTRACT)\n"
        "    plate = extrude(sk.sketch, amount=5)\n"
        "    show_object(plate)\n"
        "\n"
        "  Validity:\n"
        "    Every successful run reports `is_valid` in metrics. If false, the\n"
        "    geometry has self-intersections, unclosed shells, or inverted\n"
        "    normals — `agentcad inspect` on the STEP gives the diagnostic.\n"
        "\n"
        "  ShapeList footgun — boolean ops can return a list, not a single shape:\n"
        "    `a - b - c` and similar chained ops return `Self | ShapeList[Self]`.\n"
        "    When the cut produces multiple disconnected pieces (or in some\n"
        "    edge cases even a single piece), build123d returns a ShapeList.\n"
        "    show_object() auto-extracts a length-1 ShapeList for you, so the\n"
        "    common case Just Works. For intentional multi-body output use:\n"
        "      result = base - cut_a - cut_b      # may be Shape OR ShapeList[Shape]\n"
        "      show_assembly(result, name=\"assembly_name\")\n"
        "    If multiple pieces were accidental, call show_object() once per shape\n"
        "    while debugging:\n"
        "      result = base - cut_a - cut_b      # may be Shape OR ShapeList[Shape]\n"
        "      if hasattr(result, '__iter__'):\n"
        "          for s in result: show_object(s)\n"
        "      else:\n"
        "          show_object(result)\n"
        "    Or fuse pieces back into one part with\n"
        "    `Compound(children=list(result))` if you wanted a single output.\n"
    ),
    "parametric": (
        "Parametric scripts (build123d):\n"
        "  Declare parameters as top-level literal assignments:\n"
        "    length = 50.0\n"
        "    width  = 20.0\n"
        "    plate  = Box(length, width, 5)\n"
        "    show_object(plate)\n"
        "\n"
        "  Override with --params on agentcad run:\n"
        "    agentcad run script.py --output v2 --params length=100,width=30\n"
        "\n"
        "  Supported types: int, float, str, bool.\n"
        "  Type coercion: bool ('true'/'false') > int > float > string.\n"
        "  key=value pairs are comma-separated.\n"
        "\n"
        "  Auto-detection rules: only top-level `name = <literal>` assignments\n"
        "  are detected as parameters. Names assigned to expressions (e.g.\n"
        "  `plate = Box(...)`) are NOT parameters and cannot be overridden.\n"
        "\n"
        "  Errors:\n"
        "    Unknown parameter name → status 'error' with available names.\n"
        "    Bad format (no '=') → status 'error'.\n"
        "    Both return immediately without consuming a version number.\n"
        "\n"
        "  Params are recorded in JSON output and meta.json.\n"
        "  agentcad diff shows parameter changes between versions.\n"
    ),
    "workflow": (
        "Typical workflow (build123d project):\n"
        "  1. agentcad init --name myproject --runtime build123d\n"
        "  2. Write a script (script.py) using build123d primitives — see\n"
        "     'agentcad docs preamble' for what's pre-injected and\n"
        "     'agentcad docs quickstart' for examples.\n"
        "  3. agentcad run script.py --output label [--render iso] [--export stl,glb]\n"
        "  4. agentcad measure v1_label/output.step — check dimensions and feature sizes.\n"
        "  5. agentcad check-spec v1_label/output.step spec.json — compare against intent.\n"
        "  6. agentcad render v1_label/output.step --view front,top --zoom 1.5\n"
        "  7. agentcad export v1_label/output.step --format stl,glb\n"
        "  8. agentcad context — review project state.\n"
        "  9. agentcad diff 1 2 — compare versions.\n"
    ),
    "examples": (
        "Worked examples (build123d):\n"
        "\n"
        "  Example 1 — plate with corner holes and rounded edges:\n"
        "    plate = Box(60, 40, 5)\n"
        "    plate = fillet(plate.edges().filter_by(Axis.Z), 4)\n"
        "    for x in (-20, 20):\n"
        "        for y in (-10, 10):\n"
        "            plate -= Cylinder(2.5, 10).translate((x, y, 0))\n"
        "    show_object(plate)\n"
        "  Run:  agentcad run plate.py --output v1 --render iso\n"
        "\n"
        "  Example 2 — parametric L-bracket:\n"
        "    arm_len  = 50\n"
        "    arm_wid  = 25\n"
        "    thick    = 4\n"
        "    bolt_dia = 6\n"
        "\n"
        "    horiz = Box(arm_len, arm_wid, thick).translate((arm_len/2, arm_wid/2, thick/2))\n"
        "    vert  = Box(thick, arm_wid, arm_len).translate((thick/2, arm_wid/2, arm_len/2))\n"
        "    bracket = horiz + vert\n"
        "\n"
        "    h_hole = Cylinder(bolt_dia/2, 10).translate((arm_len-15, arm_wid/2, thick/2))\n"
        "    v_hole = Cylinder(bolt_dia/2, 10, rotation=(0,90,0)).translate(\n"
        "        (thick/2, arm_wid/2, arm_len-15))\n"
        "    bracket = bracket - h_hole - v_hole\n"
        "    show_object(bracket)\n"
        "  Run:  agentcad run bracket.py --output base\n"
        "        agentcad run bracket.py --output bigger --params arm_len=80\n"
        "\n"
        "  Example 3 — gear-blank with central bore (parametric):\n"
        "    module     = 2.0\n"
        "    teeth      = 20\n"
        "    thickness  = 5.0\n"
        "    bore_dia   = 8.0\n"
        "\n"
        "    tip_radius = module * teeth / 2.0 + module\n"
        "    blank = Cylinder(radius=tip_radius, height=thickness).translate(\n"
        "        (0, 0, thickness / 2.0))\n"
        "    bore  = Cylinder(radius=bore_dia / 2.0, height=thickness * 3).translate(\n"
        "        (0, 0, thickness / 2.0))\n"
        "    show_object(blank - bore)\n"
        "  Run:  agentcad run gear.py --output gear_v1 --render iso\n"
        "        agentcad run gear.py --output gear_big \\\n"
        "            --params teeth=32,module=2.5,bore_dia=12\n"
        "\n"
        "  Known limitation: the involute_gear_profile helper currently emits\n"
        "  a self-intersecting wire that doesn't extrude into a valid disc —\n"
        "  see issue #68. For now, cylinder-blank stand-ins like the one above\n"
        "  are the recommended recipe for gear-shaped bodies in build123d mode.\n"
    ),
    "editing": (
        "Editing existing CAD files — the M60 edit journey:\n"
        "\n"
        "  Workflow: agent receives a STEP/BREP, makes specific changes,\n"
        "  and the tool tracks edits as versioned diffs.\n"
        "\n"
        "  1. Import the file (becomes v1 with provenance):\n"
        "       agentcad import vendor.step --init\n"
        "\n"
        "  2. Inspect with --ids to see addressable faces / edges:\n"
        "       agentcad inspect v1_vendor/output.step --ids\n"
        "       # JSON now includes solids[], faces[{id,area,centroid,normal,bbox}],\n"
        "       # edges[{id,length,endpoints}]. Pick the ID(s) you want to edit.\n"
        "\n"
        "  3. Edit in build123d using load_step + pick_face / pick_edge:\n"
        "       from build123d import *\n"
        "       base = load_step('v1_vendor/output.step')\n"
        "       top_face = pick_face(base, 7)            # face ID from inspect\n"
        "       result = base.fillet(0.5, top_face.edges())\n"
        "       show_object(result)\n"
        "\n"
        "  4. Run — auto-diffs against the imported baseline:\n"
        "       agentcad run edit.py --output filleted\n"
        "\n"
        "  ID stability: face/edge IDs are 1-indexed and stable WITHIN a shape\n"
        "  (same shape, same IDs every inspect). They are NOT stable across\n"
        "  edits — even a small fillet can renumber faces. Re-run\n"
        "  `inspect --ids` after each edit to get current IDs.\n"
        "\n"
        "  Helpers shipped with the edit pipeline (build123d topology helpers\n"
        "  plus runtime-neutral annular helpers):\n"
        "    load_step(path) -> Part         load a STEP/STP/BREP as a Part\n"
        "    load_step_shape(path) -> TopoDS  raw OCCT shape (escape hatch)\n"
        "    pick_face(shape, id) -> Face    look up by ID from inspect --ids\n"
        "    pick_edge(shape, id) -> Edge    look up by ID from inspect --ids\n"
        "    fillet_edges(shape, ids, r)     fillet edges by ID, radius r\n"
        "    chamfer_edges(shape, ids, d)    chamfer edges by ID, distance d\n"
        "    shell_faces(shape, ids, t)      hollow shape, opening face IDs;\n"
        "                                    negative t = inward (typical wall)\n"
        "                                    positive t = outward (rare)\n"
        "    split_by_plane(shape, plane)    cut shape with infinite plane;\n"
        "                                    returns (below, above) tuple.\n"
        "                                    plane: 'XY' / 'XZ' / 'YZ' or a\n"
        "                                    build123d Plane (e.g. Plane.XY.offset(5)).\n"
        "    cut_pocket(shape, face_id, profile, depth)\n"
        "                                    cut a pocket on the picked face by\n"
        "                                    extruding profile inward by depth.\n"
        "                                    profile is a build123d Sketch / Face.\n"
        "    boss(shape, face_id, profile, height)\n"
        "                                    add a raised feature on the picked\n"
        "                                    face by extruding profile outward.\n"
        "                                    Same shape as cut_pocket but adds\n"
        "                                    instead of subtracts.\n"
        "    annular_boss(center, inner_radius, outer_radius, height, z_min=0)\n"
        "                                    create only a raised annular land;\n"
        "                                    accepts diameter kwargs too.\n"
        "    raise_annulus(source, *, center, inner_diameter, outer_diameter, height, z=0)\n"
        "                                    add a raised annular land to a STEP\n"
        "                                    path or raw shape. Returns a compound\n"
        "                                    by default, avoiding fragile fuses.\n"
        "    Example feature ops:\n"
        "      profile = Sketch() + Circle(radius=3)\n"
        "      result = cut_pocket(base, face_id=7, profile=profile, depth=4)\n"
        "      result = boss(base, face_id=7, profile=profile, height=4)\n"
        "      raw = load_step_shape('v1_vendor/output.step')\n"
        "      result = raise_annulus(raw, center=(-105, -30),\n"
        "                            inner_diameter=74, outer_diameter=134.2,\n"
        "                            height=10, z=0)\n"
        "      show_object(Compound(result))\n"
        "    `ids` accepts a single int or a list. Out-of-range raises\n"
        "    ValueError pointing back at `inspect --ids`.\n"
        "    Limitation: shell_faces can't open a face that has an inner\n"
        "    loop (e.g. a through-hole pierces it). Pick a different face,\n"
        "    or plug the hole before shelling and re-cut afterward.\n"
        "\n"
        "  CadQuery users: most topology-ID helpers above are build123d-only;\n"
        "  annular_boss and raise_annulus are runtime-neutral raw-shape helpers.\n"
        "  For other edits, use the CadQuery-native imported STEP path:\n"
        "    from cadquery import importers\n"
        "    base = importers.importStep('v1_vendor/output.step')\n"
        "    # then native CadQuery selectors (faces('>Z') etc.)\n"
        "  Calling pick_face / pick_edge / load_step in a CadQuery script\n"
        "  fails fast with a validation error pointing at this fallback.\n"
    ),
}


def get_sections(runtime):
    """Return the sections dict for ``runtime`` (overlay applied, base unchanged)."""
    if runtime == "build123d":
        merged = dict(SECTIONS)
        merged.update(BUILD123D_OVERLAY)
        return merged
    return SECTIONS


@click.command()
@click.argument("section", required=False, default=None)
@click.option(
    "--runtime",
    default=None,
    type=click.Choice(["cadquery", "build123d"]),
    help=(
        "Show docs for a specific runtime. Default: read project mode "
        "from agentcad.json, fall back to the global default runtime."
    ),
)
def docs(section, runtime):
    """Show agentcad documentation."""
    # Walk parents so `agentcad docs` honors the project manifest even when
    # invoked from a subdir. Other commands (`run`, `inspect`) keep cwd-only
    # semantics since they write artifacts relative to cwd.
    project_rt = dispatch.project_runtime(search_parents=True)
    # "Implicit default" == we're about to show whatever the global default
    # is purely because there's nothing telling us otherwise. Surface a hint
    # so fresh users don't silently read wrong-engine docs for a project
    # they just haven't cd'd into yet.
    implicit_default = runtime is None and project_rt is None
    effective_runtime = runtime or project_rt or dispatch.DEFAULT_RUNTIME
    sections = get_sections(effective_runtime)

    other_runtime = "build123d" if effective_runtime == "cadquery" else "cadquery"
    runtime_hint = (
        f"Showing {effective_runtime} docs (default outside a pinned project). "
        f"For {other_runtime}, run from a project initialized with "
        f"'agentcad init --runtime {other_runtime}' or pass '--runtime {other_runtime}'."
    ) if implicit_default else None

    if section is not None:
        if section not in sections:
            response = {
                "command": "docs",
                "status": "error",
                "runtime": effective_runtime,
                "message": f"Unknown section '{section}'. "
                           f"Available: {', '.join(sorted(sections))}",
            }
            if runtime_hint:
                response["runtime_hint"] = runtime_hint
            click.echo(json.dumps(response))
            sys.exit(1)

        response = {
            "command": "docs",
            "status": "success",
            "runtime": effective_runtime,
            "section": section,
            "content": sections[section],
        }
        if runtime_hint:
            response["runtime_hint"] = runtime_hint
        click.echo(json.dumps(response))
        return

    # No section — return full documentation
    full_content = "\n".join(sections.values())

    response = {
        "command": "docs",
        "status": "success",
        "runtime": effective_runtime,
        "sections": sorted(sections.keys()),
        "content": full_content,
    }
    if runtime_hint:
        response["runtime_hint"] = runtime_hint
    click.echo(json.dumps(response))
